test_string = [
    ("Je veux aller à Marseille à partir de Paris", ["Lyon", "Marseille"]),
    ("Je veux visiter Lyon en partant de Bordeaux et en passant par Nantes", ["Bordeaux", "Nantes", "Lyon"]),
    ("Je veux faire Lyon Gare De l'est Marseille", ["Lyon", "Marseille"]),
    ("Je veux aller à Lyon après être allé à Toulouse depuis Paris", ["Paris", "Toulouse", "Lyon"]),
    ("Lyon Marseille", ["Lyon", "Marseille"]),
    ("Je suis à Lyon et je veux aller à Nancy avec mon amis Frank que je récupère à Toulouse", ["Lyon", "Toulouse", "Nancy"]),
    ("J'aimerais aller d'Orléans à Lyon puis dans les Vosges", ["Orléans", "Lyon", "Vosges"]),
    ("Je veux partir de Toulouse et visiter Lyon depuis la destination de Nancy", ["Toulouse", "Nancy", "Lyon"]),
    ("Je veux prendre le train de Toulouse à destination de Nice et Nancy", ["Toulouse", "Colmar", "Nancy"]),
    ("Je souhaite aller à Rome", "Invalid Sentence."),
    ("Je veux aller à Paris", "Invalid Sentence."),
    ("Je veux partir de Toulouse et visiter Lyon depuis Nancy", ["Toulouse", "Nancy", "Lyon"]),
    ("Je veux voyager de Toulouse pour visiter Lyon en passant par Nancy", ["Toulouse", "Nancy", "Lyon"]),
    ("Nancy en provenance de Toulouse", ["Toulouse", "Nancy"]),
    ("Je veux prendre le train à Toulouse à destination de Nancy", ["Toulouse", "Nancy"]),
    ("Je veux aller de Toulouse à Nancy", ["Toulouse", "Nancy"]),
    ("Je souhaite trouver des trains pour aller à Cannes le 31/11/2021 en passant par Marseille. ", ["Cannes", "Marseille"]),
    ("Je veux réserver aller-retour le même jour entre Lyon et Toulouse le 05 Décembre. ", ["Lyon", "Toulouse"]),
    ("J'aimerai partir de Lille pour arriver à Lyon. ", ["Lille", "Lyon"]),
    ("En partant de Strasbourg je souhaiterai me rendre à Nancy le 23 Décembre. ", ["Strasbourg", "Nancy"]),
    ("je veux aller de la Gare de Lyon à la Gare de Perrache.", ["Gare de Lyon", "Gare de Perrache"]),
    ("Lyon à Marseille par Grenoble. ", ["Lyon", "Grenoble", "Marseille"]),
    ("Grenoble de Lyon ", ["Lyon", "Grenoble"]),
    ("Je souhaiterais me rendre à Carcassonne en partant de Toulouse ", ["Toulouse", "Carcassonne"]),
    ("Veux aller au Havre en passant par Paris en partant de Lyon ", ["Lyon", "Paris", "Havre"]),
    ("Trouves moi un trajet Marseille Cannes ", ["Marseille ", "Cannes"]),
    ("De Colomiers à Toulouse à Saint-Sulpice ", ["Colomiers", "Toulouse", "Saint-Sulpice"]),
    ("Direction Paris en provenance de Nantes ", ["Nantes", "Paris"]),
    ("Départ de Lyon, je fais une escale à Toulouse, et je vais sur Biarritz ", ["Lyon", "Toulouse", "Biarritz"]),
    ("Go Metz, je suis à Paris ", ["Paris", "Metz"]),
]
